version: '3'

services:

  influxdb:
    image: influxdb
    volumes:
      - influxdb-data:/var/lib/influxdb
    ports:
      - "127.0.0.1:8086:8086"

  grafana:
    image: grafana/grafana
    volumes:
      #- ./data/grafana:/var/lib/grafana
      - grafana-data:/var/lib/grafana
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      INFLUXDB_URL: http://influxdb:8086
    links:
      - influxdb

  # chronograf:
  #   image: chronograf
  #   volumes:
  #     - chronograf-data:/var/lib/chronograf
  #   environment:
  #     INFLUXDB_URL: http://influxdb:8086
  #   ports:
  #     - "127.0.0.1:8888:8888"
  #   links:
  #     - influxdb

  influxdb-cli:
    image: influxdb:1.3.5
    entrypoint:
      - influx
      - -host
      - influxdb
    links:
      - influxdb

  web:
    image: php:7.3-apache
    volumes:
      - ./site:/var/www/html
    environment:
      INFLUXDB_URL: http://influxdb:8086
    ports:
      - "127.0.0.1:8080:80"
    links:
      - influxdb

volumes:
  influxdb-data:
    driver: local

  grafana-data:
    driver: local

  # chronograf-data:
  #   driver: local
