<?php
// Takes raw data from the request
$json = file_get_contents('php://input');

// Converts it into a PHP object
$data = json_decode($json);

$feeling = $data->feeling;
if(isIllegal($feeling) === true) {
    die("Illegal feeling");
}

$account = $_COOKIE["c3account"];
if(isIllegal($account) === true) {
    die("Illegal value account");
}
if($account == "") {
    $account = "anonymous";
}

// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, 'http://influxdb:8086/write?db=feel');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, "feel,type=" . $feeling . ",device=" . $account . " value=1");
curl_setopt($ch, CURLOPT_POST, 1);

$headers = array();
$headers[] = 'Content-Type: application/x-www-form-urlencoded';
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close($ch);



function isIllegal($test) {
    $badCodes = array("\n", ",", "=", " ");
    foreach ($badCodes as $code) {
        $isProblem = strpos($test , $code);
        if($isProblem !== false) {
            return true;
        }
    }
    return false;
}

?>
